1letter/svg flag support
plone/plone.i18n pull request #36
Opened 2021-04-07 13:30 UTC by 1letter

use SVG Flags in Language Selector

2021-04-07 13:30 UTC, mister-roboto commented
@1letter thanks for creating this Pull Request and help improve Plone!

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass.

Whenever you feel that the pull request is ready to be tested, either start all jenkins jobs pull requests by yourself, or simply add a comment in this pull request stating:

```
@jenkins-plone-org please run jobs
```

With this simple comment all the jobs will be started automatically.

Happy hacking!

2021-04-07 21:01 UTC, thet requested changes
LGTM except for one infrastructure task:
- branch away a ``4.x`` branch from current master
- increase the version in setup.py to ``5.0.0.dev0``
- add a PR to buildout.coredev 5.2 and maybe other 5.x branches changing the plone.app.i18n branch from master to ``4.x`` in sources.cfg.

2021-04-27 18:49 UTC, 1letter commented
@thet only for my better understanding:
- the current master without my changes, but with an increased version in setup.py?
- my changes only for plone 6, why should i add this to `buildout.coredev 5.2`
- the merge of this PR going in the new branch `4.x` with the increased version `5.0.0.dev0` after running tests in buildout.coredev?

2022-05-20 15:07 UTC, closed without merging

2022-05-20 15:07 UTC, jensens commented
see #42